# -*- coding: utf-8 -*-
"""Code Lab 1 - Assessment 1 - Chapter 1 - Exercise 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mhL5CvAIce1fw3FfoENKiPMkb1EiYuZC
"""

#Exercise 2: Print the Version of Python

!python --version