# -*- coding: utf-8 -*-
"""Code Lab 1 - Assessment 1 - Chapter 1 - Exercise 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gSuGLSIMXQoaG5ouXGh-esOxIx-PrrCs
"""

#Exercise 5: Compute Area of Circle

pi = 3.14
r = int(input("Enter the radius: "))
area = pi * r**2

print("The area of the circle based on your radius is:", area)