# -*- coding: utf-8 -*-
"""Code Lab 1 - Assessment 1 - Chapter 1 - Exercise 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14SvJapGQ4BSvCvg6sJZeFETXaXHaTSB2
"""

#Exercise 4: Strings Concatination

num1 = "1"
num2 = "4"
num3 = "3"

print(num1 + num2 + num3)