# -*- coding: utf-8 -*-
"""Code Lab 1 - Assessment 1 - Chapter 1 - Exercise 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UaF6Lh5-Al3t9NWSEigRzhUHUefxiudX
"""

#Exercise 1: Print Strings

print("""Twinkle, twinkle, little star,
How I wonder what you are!
Up above the world so high,
Like a diamond in the sky.
Twinkle, twinkle, little star,
How I wonder what you are!""")