# -*- coding: utf-8 -*-
"""Code Lab 1 - Assessment 1 - Chapter 1 - Exercise 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/125ZdQoSnf8_ixnNimW88Fe5rFq6C_1kw
"""

#Exercise 3: Print Date and Time

import time 

current_time = time.ctime()
print(current_time)